/**
 * HubLab Android Compiler
 *
 * Genera proyectos Android Studio completos con código Jetpack Compose nativo.
 * Output: Proyecto listo para abrir en Android Studio y compilar/publicar.
 */

import { PlatformCompiler, ThemeProcessor } from '../base'
import type {
  TargetPlatform,
  AppComposition,
  CapsuleInstance,
  CapsuleDefinition,
  AndroidImplementation,
  AndroidAppConfig,
  GeneratedFile,
  CompilationResult,
  ThemeConfig
} from '../../capsules-multiplatform/types'

export class AndroidCompiler extends PlatformCompiler {
  readonly platform: TargetPlatform = 'android'
  readonly name = 'Android Jetpack Compose Compiler'

  private config: AndroidAppConfig = {
    framework: 'compose',
    packageName: 'com.hublab.app',
    minSdk: 24,
    targetSdk: 34,
    permissions: ['INTERNET']
  }

  /**
   * Configura opciones específicas de Android
   */
  configure(config: Partial<AndroidAppConfig>): void {
    this.config = { ...this.config, ...config }
  }

  /**
   * Compila composición a proyecto Android Studio
   */
  async compile(composition: AppComposition): Promise<CompilationResult> {
    this.reset()

    // Merge config from composition if provided
    if (composition.platformConfig?.android) {
      this.config = { ...this.config, ...composition.platformConfig.android }
    }

    const files: GeneratedFile[] = []
    const appName = this.toPascalCase(composition.name)
    const packagePath = this.config.packageName.replace(/\./g, '/')

    try {
      // 1. MainActivity.kt
      files.push(this.generateMainActivity(composition, appName, packagePath))

      // 2. Theme files
      files.push(...this.generateTheme(composition, appName, packagePath))

      // 3. Components (Cápsulas)
      const componentFiles = this.generateComponents(composition, packagePath)
      files.push(...componentFiles)

      // 4. Screens
      files.push(this.generateHomeScreen(composition, appName, packagePath))

      // 5. Navigation (si hay múltiples screens)
      files.push(this.generateNavigation(composition, appName, packagePath))

      // 6. AndroidManifest.xml
      files.push(this.generateManifest(composition, appName))

      // 7. build.gradle.kts (app level)
      files.push(this.generateAppBuildGradle(composition))

      // 8. build.gradle.kts (project level)
      files.push(this.generateProjectBuildGradle())

      // 9. settings.gradle.kts
      files.push(this.generateSettingsGradle(appName))

      // 10. gradle.properties
      files.push(this.generateGradleProperties())

      // 11. strings.xml
      files.push(this.generateStrings(composition, appName))

      // 12. themes.xml
      files.push(this.generateThemesXml(composition, appName))

      // 13. README
      files.push(this.generateReadme(composition, appName))

      return this.createResult(true, files)

    } catch (error) {
      this.addError('COMPILATION_FAILED', error instanceof Error ? error.message : 'Unknown error')
      return this.createResult(false, files)
    }
  }

  // ============================================
  // GENERATORS
  // ============================================

  private generateMainActivity(
    composition: AppComposition,
    appName: string,
    packagePath: string
  ): GeneratedFile {
    return {
      path: `app/src/main/java/${packagePath}/MainActivity.kt`,
      content: `/**
 * ${appName}
 * Generated by HubLab - https://hublab.dev
 */

package ${this.config.packageName}

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Surface
import androidx.compose.ui.Modifier
import ${this.config.packageName}.ui.theme.${appName}Theme
import ${this.config.packageName}.ui.screens.HomeScreen

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContent {
            ${appName}Theme {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    HomeScreen()
                }
            }
        }
    }
}
`,
      encoding: 'utf-8',
      language: 'kotlin'
    }
  }

  private generateTheme(
    composition: AppComposition,
    appName: string,
    packagePath: string
  ): GeneratedFile[] {
    const theme = composition.theme

    return [
      // Color.kt
      {
        path: `app/src/main/java/${packagePath}/ui/theme/Color.kt`,
        content: `/**
 * Color definitions for ${appName}
 * Generated by HubLab - https://hublab.dev
 */

package ${this.config.packageName}.ui.theme

import androidx.compose.ui.graphics.Color

// Primary colors
val Primary = Color(0xFF${theme.colors.primary.replace('#', '')})
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFF${this.lightenColor(theme.colors.primary, 0.8).replace('#', '')})
val OnPrimaryContainer = Color(0xFF${theme.colors.primary.replace('#', '')})

// Secondary colors
val Secondary = Color(0xFF${theme.colors.secondary.replace('#', '')})
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFF${this.lightenColor(theme.colors.secondary, 0.8).replace('#', '')})
val OnSecondaryContainer = Color(0xFF${theme.colors.secondary.replace('#', '')})

// Accent/Tertiary colors
val Tertiary = Color(0xFF${theme.colors.accent.replace('#', '')})
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFF${this.lightenColor(theme.colors.accent, 0.8).replace('#', '')})
val OnTertiaryContainer = Color(0xFF${theme.colors.accent.replace('#', '')})

// Background & Surface
val Background = Color(0xFF${theme.colors.background.replace('#', '')})
val OnBackground = Color(0xFF${theme.colors.text.primary.replace('#', '')})
val Surface = Color(0xFF${theme.colors.surface.replace('#', '')})
val OnSurface = Color(0xFF${theme.colors.text.primary.replace('#', '')})
val SurfaceVariant = Color(0xFFF5F5F5)
val OnSurfaceVariant = Color(0xFF${theme.colors.text.secondary.replace('#', '')})

// Status colors
val Error = Color(0xFF${theme.colors.error.replace('#', '')})
val OnError = Color(0xFFFFFFFF)
val Success = Color(0xFF${theme.colors.success.replace('#', '')})
val Warning = Color(0xFF${theme.colors.warning.replace('#', '')})

// Outline
val Outline = Color(0xFFE0E0E0)
val OutlineVariant = Color(0xFFF0F0F0)
`,
        encoding: 'utf-8',
        language: 'kotlin'
      },

      // Theme.kt
      {
        path: `app/src/main/java/${packagePath}/ui/theme/Theme.kt`,
        content: `/**
 * Theme configuration for ${appName}
 * Generated by HubLab - https://hublab.dev
 */

package ${this.config.packageName}.ui.theme

import android.app.Activity
import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.SideEffect
import androidx.compose.ui.graphics.toArgb
import androidx.compose.ui.platform.LocalView
import androidx.core.view.WindowCompat

private val LightColorScheme = lightColorScheme(
    primary = Primary,
    onPrimary = OnPrimary,
    primaryContainer = PrimaryContainer,
    onPrimaryContainer = OnPrimaryContainer,
    secondary = Secondary,
    onSecondary = OnSecondary,
    secondaryContainer = SecondaryContainer,
    onSecondaryContainer = OnSecondaryContainer,
    tertiary = Tertiary,
    onTertiary = OnTertiary,
    tertiaryContainer = TertiaryContainer,
    onTertiaryContainer = OnTertiaryContainer,
    background = Background,
    onBackground = OnBackground,
    surface = Surface,
    onSurface = OnSurface,
    surfaceVariant = SurfaceVariant,
    onSurfaceVariant = OnSurfaceVariant,
    error = Error,
    onError = OnError,
    outline = Outline,
    outlineVariant = OutlineVariant
)

private val DarkColorScheme = darkColorScheme(
    primary = Primary,
    onPrimary = OnPrimary,
    secondary = Secondary,
    onSecondary = OnSecondary,
    tertiary = Tertiary,
    onTertiary = OnTertiary,
    background = Color(0xFF121212),
    onBackground = Color(0xFFFFFFFF),
    surface = Color(0xFF1E1E1E),
    onSurface = Color(0xFFFFFFFF)
)

@Composable
fun ${appName}Theme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit
) {
    val colorScheme = if (darkTheme) DarkColorScheme else LightColorScheme
    val view = LocalView.current

    if (!view.isInEditMode) {
        SideEffect {
            val window = (view.context as Activity).window
            window.statusBarColor = colorScheme.primary.toArgb()
            WindowCompat.getInsetsController(window, view).isAppearanceLightStatusBars = !darkTheme
        }
    }

    MaterialTheme(
        colorScheme = colorScheme,
        typography = Typography,
        content = content
    )
}
`,
        encoding: 'utf-8',
        language: 'kotlin'
      },

      // Type.kt
      {
        path: `app/src/main/java/${packagePath}/ui/theme/Type.kt`,
        content: `/**
 * Typography for ${appName}
 * Generated by HubLab - https://hublab.dev
 */

package ${this.config.packageName}.ui.theme

import androidx.compose.material3.Typography
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.sp

val Typography = Typography(
    displayLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Bold,
        fontSize = 57.sp,
        lineHeight = 64.sp,
        letterSpacing = (-0.25).sp
    ),
    displayMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Bold,
        fontSize = 45.sp,
        lineHeight = 52.sp,
        letterSpacing = 0.sp
    ),
    displaySmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Bold,
        fontSize = 36.sp,
        lineHeight = 44.sp,
        letterSpacing = 0.sp
    ),
    headlineLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.SemiBold,
        fontSize = 32.sp,
        lineHeight = 40.sp,
        letterSpacing = 0.sp
    ),
    headlineMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.SemiBold,
        fontSize = 28.sp,
        lineHeight = 36.sp,
        letterSpacing = 0.sp
    ),
    headlineSmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.SemiBold,
        fontSize = 24.sp,
        lineHeight = 32.sp,
        letterSpacing = 0.sp
    ),
    titleLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 22.sp,
        lineHeight = 28.sp,
        letterSpacing = 0.sp
    ),
    titleMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 16.sp,
        lineHeight = 24.sp,
        letterSpacing = 0.15.sp
    ),
    titleSmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 14.sp,
        lineHeight = 20.sp,
        letterSpacing = 0.1.sp
    ),
    bodyLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = 16.sp,
        lineHeight = 24.sp,
        letterSpacing = 0.5.sp
    ),
    bodyMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = 14.sp,
        lineHeight = 20.sp,
        letterSpacing = 0.25.sp
    ),
    bodySmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.4.sp
    ),
    labelLarge = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 14.sp,
        lineHeight = 20.sp,
        letterSpacing = 0.1.sp
    ),
    labelMedium = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 12.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.5.sp
    ),
    labelSmall = TextStyle(
        fontFamily = FontFamily.Default,
        fontWeight = FontWeight.Medium,
        fontSize = 11.sp,
        lineHeight = 16.sp,
        letterSpacing = 0.5.sp
    )
)
`,
        encoding: 'utf-8',
        language: 'kotlin'
      }
    ]
  }

  private generateComponents(composition: AppComposition, packagePath: string): GeneratedFile[] {
    const files: GeneratedFile[] = []
    const usedCapsules = this.collectUsedCapsules(composition)

    for (const capsuleId of usedCapsules) {
      const capsule = this.getCapsule(capsuleId)

      if (!capsule) {
        this.addWarning('CAPSULE_NOT_FOUND', `Capsule "${capsuleId}" not found in registry`, capsuleId)
        continue
      }

      const impl = capsule.platforms.android as AndroidImplementation | undefined

      if (!impl) {
        this.addWarning('NO_ANDROID_IMPL', `Capsule "${capsuleId}" has no Android implementation`, capsuleId)
        continue
      }

      const componentName = this.toPascalCase(capsule.name)
      const imports = impl.imports?.map(i => `import ${i}`).join('\n') || ''

      files.push({
        path: `app/src/main/java/${packagePath}/ui/components/${componentName}.kt`,
        content: `/**
 * ${componentName}
 * Generated by HubLab - https://hublab.dev
 * Capsule: ${capsule.id} v${capsule.version}
 */

package ${this.config.packageName}.ui.components

${imports}

${impl.code}
`,
        encoding: 'utf-8',
        language: 'kotlin'
      })
    }

    return files
  }

  private generateHomeScreen(
    composition: AppComposition,
    appName: string,
    packagePath: string
  ): GeneratedFile {
    const componentImports = this.generateComponentImports(composition)
    const capsuleViews = this.generateCapsuleViews(composition.root, 4)

    return {
      path: `app/src/main/java/${packagePath}/ui/screens/HomeScreen.kt`,
      content: `/**
 * HomeScreen
 * Generated by HubLab - https://hublab.dev
 */

package ${this.config.packageName}.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.compose.ui.tooling.preview.Preview
${componentImports}
import ${this.config.packageName}.ui.theme.${appName}Theme

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun HomeScreen() {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("${composition.name}") },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.primary,
                    titleContentColor = MaterialTheme.colorScheme.onPrimary
                )
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .padding(16.dp)
                .verticalScroll(rememberScrollState()),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
${capsuleViews}
        }
    }
}

@Preview(showBackground = true)
@Composable
fun HomeScreenPreview() {
    ${appName}Theme {
        HomeScreen()
    }
}
`,
      encoding: 'utf-8',
      language: 'kotlin'
    }
  }

  private generateNavigation(
    composition: AppComposition,
    appName: string,
    packagePath: string
  ): GeneratedFile {
    return {
      path: `app/src/main/java/${packagePath}/navigation/AppNavigation.kt`,
      content: `/**
 * Navigation for ${appName}
 * Generated by HubLab - https://hublab.dev
 */

package ${this.config.packageName}.navigation

import androidx.compose.runtime.Composable
import androidx.navigation.NavHostController
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import ${this.config.packageName}.ui.screens.HomeScreen

sealed class Screen(val route: String) {
    object Home : Screen("home")
    // Add more screens as needed
}

@Composable
fun AppNavigation(
    navController: NavHostController = rememberNavController()
) {
    NavHost(
        navController = navController,
        startDestination = Screen.Home.route
    ) {
        composable(Screen.Home.route) {
            HomeScreen()
        }
        // Add more composable routes as needed
    }
}
`,
      encoding: 'utf-8',
      language: 'kotlin'
    }
  }

  private generateManifest(composition: AppComposition, appName: string): GeneratedFile {
    const permissions = this.config.permissions
      .map(p => `    <uses-permission android:name="android.permission.${p}" />`)
      .join('\n')

    return {
      path: 'app/src/main/AndroidManifest.xml',
      content: `<?xml version="1.0" encoding="UTF-8"?>
<!--
  ${appName}
  Generated by HubLab - https://hublab.dev
-->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

${permissions}

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.${appName}">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:label="@string/app_name"
            android:theme="@style/Theme.${appName}">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

    </application>
</manifest>`,
      encoding: 'utf-8',
      language: 'xml'
    }
  }

  private generateAppBuildGradle(composition: AppComposition): GeneratedFile {
    const deps = this.collectDependencies(composition)
    const extraDeps = deps
      .filter(d => !d.startsWith('androidx.compose'))
      .map(d => `    implementation("${d}")`)
      .join('\n')

    return {
      path: 'app/build.gradle.kts',
      content: `/**
 * App-level build configuration
 * Generated by HubLab - https://hublab.dev
 */

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

android {
    namespace = "${this.config.packageName}"
    compileSdk = ${this.config.targetSdk}

    defaultConfig {
        applicationId = "${this.config.packageName}"
        minSdk = ${this.config.minSdk}
        targetSdk = ${this.config.targetSdk}
        versionCode = 1
        versionName = "${composition.version || '1.0.0'}"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        compose = true
    }
}

dependencies {
    // Core Android
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.activity.compose)

    // Compose
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.ui)
    implementation(libs.androidx.ui.graphics)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.material3)

    // Navigation
    implementation(libs.androidx.navigation.compose)

    // Additional dependencies
${extraDeps}

    // Testing
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}
`,
      encoding: 'utf-8',
      language: 'kotlin'
    }
  }

  private generateProjectBuildGradle(): GeneratedFile {
    return {
      path: 'build.gradle.kts',
      content: `/**
 * Project-level build configuration
 * Generated by HubLab - https://hublab.dev
 */

plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.kotlin.compose) apply false
}
`,
      encoding: 'utf-8',
      language: 'kotlin'
    }
  }

  private generateSettingsGradle(appName: string): GeneratedFile {
    return {
      path: 'settings.gradle.kts',
      content: `/**
 * Settings configuration
 * Generated by HubLab - https://hublab.dev
 */

pluginManagement {
    repositories {
        google {
            content {
                includeGroupByRegex("com\\\\.android.*")
                includeGroupByRegex("com\\\\.google.*")
                includeGroupByRegex("androidx.*")
            }
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "${appName}"
include(":app")
`,
      encoding: 'utf-8',
      language: 'kotlin'
    }
  }

  private generateGradleProperties(): GeneratedFile {
    return {
      path: 'gradle.properties',
      content: `# Project-wide Gradle settings
# Generated by HubLab - https://hublab.dev

# Performance
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Compose
android.enableJetifier=false
`,
      encoding: 'utf-8',
      language: 'properties'
    }
  }

  private generateStrings(composition: AppComposition, appName: string): GeneratedFile {
    return {
      path: 'app/src/main/res/values/strings.xml',
      content: `<?xml version="1.0" encoding="utf-8"?>
<!--
  String resources for ${appName}
  Generated by HubLab - https://hublab.dev
-->
<resources>
    <string name="app_name">${composition.name}</string>
</resources>`,
      encoding: 'utf-8',
      language: 'xml'
    }
  }

  private generateThemesXml(composition: AppComposition, appName: string): GeneratedFile {
    return {
      path: 'app/src/main/res/values/themes.xml',
      content: `<?xml version="1.0" encoding="utf-8"?>
<!--
  Theme resources for ${appName}
  Generated by HubLab - https://hublab.dev
-->
<resources>
    <style name="Theme.${appName}" parent="android:Theme.Material.Light.NoActionBar">
        <item name="android:statusBarColor">@android:color/transparent</item>
        <item name="android:navigationBarColor">@android:color/transparent</item>
    </style>
</resources>`,
      encoding: 'utf-8',
      language: 'xml'
    }
  }

  private generateReadme(composition: AppComposition, appName: string): GeneratedFile {
    return {
      path: 'README.md',
      content: `# ${composition.name}

Generated by [HubLab](https://hublab.dev) - Universal App Compiler

## Requirements

- Android Studio Hedgehog (2023.1.1) or newer
- JDK 17
- Android SDK ${this.config.targetSdk}
- Min SDK: ${this.config.minSdk} (Android ${this.getAndroidVersion(this.config.minSdk)}+)

## Getting Started

1. Open project in Android Studio
2. Sync Gradle files
3. Select a device/emulator
4. Click Run ▶️

## Project Structure

\`\`\`
app/src/main/
├── java/${this.config.packageName.replace(/\./g, '/')}/
│   ├── MainActivity.kt       # Entry point
│   ├── ui/
│   │   ├── theme/            # Material 3 theme
│   │   │   ├── Color.kt
│   │   │   ├── Theme.kt
│   │   │   └── Type.kt
│   │   ├── components/       # HubLab capsule components
│   │   └── screens/
│   │       └── HomeScreen.kt
│   └── navigation/
│       └── AppNavigation.kt
├── res/
│   └── values/
│       ├── strings.xml
│       └── themes.xml
└── AndroidManifest.xml
\`\`\`

## Customization

### Colors
Edit \`ui/theme/Color.kt\` to customize the color scheme.

### Components
All components in \`ui/components/\` are native Jetpack Compose composables.

## Building for Release

1. Generate signing key:
   \`\`\`
   keytool -genkey -v -keystore release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias release
   \`\`\`

2. Add to \`gradle.properties\`:
   \`\`\`
   RELEASE_STORE_FILE=release-key.jks
   RELEASE_STORE_PASSWORD=your_password
   RELEASE_KEY_ALIAS=release
   RELEASE_KEY_PASSWORD=your_password
   \`\`\`

3. Build release APK:
   \`\`\`
   ./gradlew assembleRelease
   \`\`\`

## Publishing to Play Store

1. Build release bundle: \`./gradlew bundleRelease\`
2. Upload AAB to Google Play Console
3. Fill app listing details
4. Submit for review

## Support

- Documentation: https://hublab.dev/docs
- Issues: https://github.com/hublab/hublab/issues
`,
      encoding: 'utf-8',
      language: 'markdown'
    }
  }

  // ============================================
  // HELPERS
  // ============================================

  private generateComponentImports(composition: AppComposition): string {
    const usedCapsules = this.collectUsedCapsules(composition)
    const imports: string[] = []

    for (const capsuleId of usedCapsules) {
      const capsule = this.getCapsule(capsuleId)
      if (capsule) {
        const name = this.toPascalCase(capsule.name)
        imports.push(`import ${this.config.packageName}.ui.components.${name}`)
      }
    }

    return imports.join('\n')
  }

  private generateCapsuleViews(instance: CapsuleInstance, indent: number): string {
    const capsule = this.getCapsule(instance.capsuleId)
    if (!capsule) return `${' '.repeat(indent * 4)}// Capsule not found: ${instance.capsuleId}`

    const viewName = this.toPascalCase(capsule.name)
    const props = this.generateKotlinProps(instance.props, capsule)
    const spaces = ' '.repeat(indent * 4)

    let view = `${spaces}${viewName}(${props})`

    if (instance.children && instance.children.length > 0) {
      const childViews = instance.children
        .map(child => this.generateCapsuleViews(child, indent + 1))
        .join('\n')
      view = `${spaces}${viewName}(${props}) {\n${childViews}\n${spaces}}`
    }

    return view
  }

  private generateKotlinProps(props: Record<string, unknown>, capsule: CapsuleDefinition): string {
    const propDefs = capsule.props
    const parts: string[] = []

    for (const [key, value] of Object.entries(props)) {
      const def = propDefs.find(p => p.name === key)
      const kotlinKey = def?.platformMapping?.android || key

      if (def?.type === 'action') {
        parts.push(`${kotlinKey} = {}`)
      } else if (typeof value === 'string') {
        parts.push(`${kotlinKey} = "${this.escapeString(value)}"`)
      } else if (typeof value === 'boolean') {
        parts.push(`${kotlinKey} = ${value}`)
      } else if (typeof value === 'number') {
        parts.push(`${kotlinKey} = ${value}`)
      }
    }

    // Add newlines for readability if many props
    if (parts.length > 2) {
      return '\n' + parts.map(p => `                ${p}`).join(',\n') + '\n            '
    }

    return parts.join(', ')
  }

  private lightenColor(hex: string, amount: number): string {
    const rgb = this.hexToRgb(hex)
    if (!rgb) return hex

    const lighten = (c: number) => Math.round(c + (255 - c) * amount)

    const r = lighten(rgb.r).toString(16).padStart(2, '0')
    const g = lighten(rgb.g).toString(16).padStart(2, '0')
    const b = lighten(rgb.b).toString(16).padStart(2, '0')

    return `#${r}${g}${b}`
  }

  private getAndroidVersion(sdk: number): string {
    const versions: Record<number, string> = {
      21: '5.0',
      22: '5.1',
      23: '6.0',
      24: '7.0',
      25: '7.1',
      26: '8.0',
      27: '8.1',
      28: '9.0',
      29: '10',
      30: '11',
      31: '12',
      32: '12L',
      33: '13',
      34: '14'
    }
    return versions[sdk] || String(sdk)
  }
}
