/**
 * HubLab iOS Compiler
 *
 * Genera proyectos Xcode completos con código SwiftUI nativo.
 * Output: Proyecto listo para abrir en Xcode y compilar/publicar.
 */

import { PlatformCompiler, ThemeProcessor } from '../base'
import type {
  TargetPlatform,
  AppComposition,
  CapsuleInstance,
  CapsuleDefinition,
  IOSImplementation,
  IOSAppConfig,
  GeneratedFile,
  CompilationResult,
  ThemeConfig
} from '../../capsules-multiplatform/types'

export class IOSCompiler extends PlatformCompiler {
  readonly platform: TargetPlatform = 'ios'
  readonly name = 'iOS SwiftUI Compiler'

  private config: IOSAppConfig = {
    framework: 'swiftui',
    bundleId: 'com.hublab.app',
    minVersion: '15.0',
    capabilities: []
  }

  /**
   * Configura opciones específicas de iOS
   */
  configure(config: Partial<IOSAppConfig>): void {
    this.config = { ...this.config, ...config }
  }

  /**
   * Compila composición a proyecto Xcode
   */
  async compile(composition: AppComposition): Promise<CompilationResult> {
    this.reset()

    // Merge config from composition if provided
    if (composition.platformConfig?.ios) {
      this.config = { ...this.config, ...composition.platformConfig.ios }
    }

    const files: GeneratedFile[] = []
    const appName = this.toPascalCase(composition.name)

    try {
      // 1. App Entry Point
      files.push(this.generateAppEntry(appName))

      // 2. Content View (Root)
      files.push(this.generateContentView(composition, appName))

      // 3. Theme/Colors
      files.push(this.generateColors(composition.theme, appName))

      // 4. Components (Cápsulas)
      const componentFiles = this.generateComponents(composition)
      files.push(...componentFiles)

      // 5. Screens/Views
      files.push(this.generateHomeScreen(composition, appName))

      // 6. Info.plist
      files.push(this.generateInfoPlist(composition, appName))

      // 7. Package.swift (SPM)
      files.push(this.generatePackageSwift(composition, appName))

      // 8. Xcode project structure files
      files.push(this.generateXcodeProject(composition, appName))

      // 9. Assets.xcassets
      files.push(...this.generateAssets(composition, appName))

      // 10. README
      files.push(this.generateReadme(composition, appName))

      return this.createResult(true, files)

    } catch (error) {
      this.addError('COMPILATION_FAILED', error instanceof Error ? error.message : 'Unknown error')
      return this.createResult(false, files)
    }
  }

  // ============================================
  // GENERATORS
  // ============================================

  private generateAppEntry(appName: string): GeneratedFile {
    return {
      path: `${appName}/${appName}App.swift`,
      content: `//
//  ${appName}App.swift
//  ${appName}
//
//  Generated by HubLab - https://hublab.dev
//

import SwiftUI

@main
struct ${appName}App: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
`,
      encoding: 'utf-8',
      language: 'swift'
    }
  }

  private generateContentView(composition: AppComposition, appName: string): GeneratedFile {
    return {
      path: `${appName}/ContentView.swift`,
      content: `//
//  ContentView.swift
//  ${appName}
//
//  Generated by HubLab - https://hublab.dev
//

import SwiftUI

struct ContentView: View {
    var body: some View {
        HomeScreen()
    }
}

#Preview {
    ContentView()
}
`,
      encoding: 'utf-8',
      language: 'swift'
    }
  }

  private generateColors(theme: ThemeConfig, appName: string): GeneratedFile {
    return {
      path: `${appName}/Theme/Colors.swift`,
      content: `//
//  Colors.swift
//  ${appName}
//
//  Generated by HubLab - https://hublab.dev
//

${ThemeProcessor.toSwiftColors(theme)}

// MARK: - Theme Configuration
struct AppTheme {
    static let spacing: CGFloat = ${theme.spacing === 'compact' ? '12' : theme.spacing === 'relaxed' ? '20' : '16'}
    static let cornerRadius: CGFloat = ${this.getSwiftCornerRadius(theme.borderRadius)}

    struct Fonts {
        static let body = Font.system(.body)
        static let headline = Font.system(.headline)
        static let title = Font.system(.title)
        static let caption = Font.system(.caption)
    }
}
`,
      encoding: 'utf-8',
      language: 'swift'
    }
  }

  private generateComponents(composition: AppComposition): GeneratedFile[] {
    const files: GeneratedFile[] = []
    const usedCapsules = this.collectUsedCapsules(composition)

    for (const capsuleId of usedCapsules) {
      const capsule = this.getCapsule(capsuleId)

      if (!capsule) {
        this.addWarning('CAPSULE_NOT_FOUND', `Capsule "${capsuleId}" not found in registry`, capsuleId)
        continue
      }

      const impl = capsule.platforms.ios as IOSImplementation | undefined

      if (!impl) {
        this.addWarning('NO_IOS_IMPL', `Capsule "${capsuleId}" has no iOS implementation`, capsuleId)
        continue
      }

      const componentName = this.toPascalCase(capsule.name)
      const imports = impl.imports?.join('\n') || 'import SwiftUI'

      files.push({
        path: `${this.toPascalCase(composition.name)}/Components/${componentName}.swift`,
        content: `//
//  ${componentName}.swift
//  ${this.toPascalCase(composition.name)}
//
//  Generated by HubLab - https://hublab.dev
//  Capsule: ${capsule.id} v${capsule.version}
//

${imports}

${impl.code}
`,
        encoding: 'utf-8',
        language: 'swift'
      })
    }

    return files
  }

  private generateHomeScreen(composition: AppComposition, appName: string): GeneratedFile {
    const capsuleViews = this.generateCapsuleViews(composition.root, 3)
    const layout = this.getSwiftLayout(composition)

    return {
      path: `${appName}/Screens/HomeScreen.swift`,
      content: `//
//  HomeScreen.swift
//  ${appName}
//
//  Generated by HubLab - https://hublab.dev
//

import SwiftUI

struct HomeScreen: View {
    var body: some View {
        NavigationStack {
            ScrollView {
                ${layout} {
${capsuleViews}
                }
                .padding()
            }
            .navigationTitle("${composition.name}")
            .background(Color.hubLabBackground)
        }
    }
}

#Preview {
    HomeScreen()
}
`,
      encoding: 'utf-8',
      language: 'swift'
    }
  }

  private generateInfoPlist(composition: AppComposition, appName: string): GeneratedFile {
    const capabilities = this.config.capabilities || []
    const capabilityEntries = this.generateCapabilityEntries(capabilities)

    return {
      path: `${appName}/Info.plist`,
      content: `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>en</string>
    <key>CFBundleDisplayName</key>
    <string>${composition.name}</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>${this.config.bundleId}</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>${appName}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>${composition.version || '1.0.0'}</string>
    <key>CFBundleVersion</key>
    <string>1</string>
    <key>LSMinimumSystemVersion</key>
    <string>${this.config.minVersion}</string>
    <key>UILaunchScreen</key>
    <dict>
        <key>UIColorName</key>
        <string>LaunchScreenBackground</string>
    </dict>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationPortraitUpsideDown</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
${capabilityEntries}
</dict>
</plist>`,
      encoding: 'utf-8',
      language: 'xml'
    }
  }

  private generatePackageSwift(composition: AppComposition, appName: string): GeneratedFile {
    const deps = this.collectDependencies(composition)
    const packageDeps = deps
      .filter(d => d.startsWith('https://'))
      .map(d => `        .package(url: "${d}", from: "1.0.0")`)
      .join(',\n')

    const minVersion = this.config.minVersion.replace('.0', '')

    return {
      path: 'Package.swift',
      content: `// swift-tools-version:5.9
// Generated by HubLab - https://hublab.dev

import PackageDescription

let package = Package(
    name: "${appName}",
    platforms: [
        .iOS(.v${minVersion}),
        .macOS(.v13)
    ],
    products: [
        .library(
            name: "${appName}",
            targets: ["${appName}"]
        )
    ],
    dependencies: [
${packageDeps}
    ],
    targets: [
        .target(
            name: "${appName}",
            dependencies: [],
            path: "${appName}"
        ),
        .testTarget(
            name: "${appName}Tests",
            dependencies: ["${appName}"],
            path: "${appName}Tests"
        )
    ]
)
`,
      encoding: 'utf-8',
      language: 'swift'
    }
  }

  private generateXcodeProject(composition: AppComposition, appName: string): GeneratedFile {
    // Genera un archivo de configuración simplificado
    // En producción, esto generaría el .xcodeproj completo
    return {
      path: `${appName}.xcodeproj/project.pbxproj`,
      content: `// !$*UTF8*$!
{
    archiveVersion = 1;
    classes = {};
    objectVersion = 56;
    objects = {
        /* Generated by HubLab - https://hublab.dev */
        /* This is a simplified project file */
        /* For full Xcode project generation, use HubLab Pro */
    };
    rootObject = /* Project object */;
}
`,
      encoding: 'utf-8',
      language: 'pbxproj'
    }
  }

  private generateAssets(composition: AppComposition, appName: string): GeneratedFile[] {
    const theme = composition.theme
    const primaryRgb = this.hexToRgb(theme.colors.primary)
    const bgRgb = this.hexToRgb(theme.colors.background)

    return [
      {
        path: `${appName}/Assets.xcassets/Contents.json`,
        content: JSON.stringify({
          info: { author: 'hublab', version: 1 }
        }, null, 2),
        encoding: 'utf-8',
        language: 'json'
      },
      {
        path: `${appName}/Assets.xcassets/AccentColor.colorset/Contents.json`,
        content: JSON.stringify({
          colors: [{
            color: {
              'color-space': 'srgb',
              components: {
                red: primaryRgb ? (primaryRgb.r / 255).toFixed(3) : '0.231',
                green: primaryRgb ? (primaryRgb.g / 255).toFixed(3) : '0.510',
                blue: primaryRgb ? (primaryRgb.b / 255).toFixed(3) : '0.965',
                alpha: '1.000'
              }
            },
            idiom: 'universal'
          }],
          info: { author: 'hublab', version: 1 }
        }, null, 2),
        encoding: 'utf-8',
        language: 'json'
      },
      {
        path: `${appName}/Assets.xcassets/LaunchScreenBackground.colorset/Contents.json`,
        content: JSON.stringify({
          colors: [{
            color: {
              'color-space': 'srgb',
              components: {
                red: bgRgb ? (bgRgb.r / 255).toFixed(3) : '1.000',
                green: bgRgb ? (bgRgb.g / 255).toFixed(3) : '1.000',
                blue: bgRgb ? (bgRgb.b / 255).toFixed(3) : '1.000',
                alpha: '1.000'
              }
            },
            idiom: 'universal'
          }],
          info: { author: 'hublab', version: 1 }
        }, null, 2),
        encoding: 'utf-8',
        language: 'json'
      },
      {
        path: `${appName}/Assets.xcassets/AppIcon.appiconset/Contents.json`,
        content: JSON.stringify({
          images: [
            { idiom: 'universal', platform: 'ios', size: '1024x1024' }
          ],
          info: { author: 'hublab', version: 1 }
        }, null, 2),
        encoding: 'utf-8',
        language: 'json'
      }
    ]
  }

  private generateReadme(composition: AppComposition, appName: string): GeneratedFile {
    return {
      path: 'README.md',
      content: `# ${composition.name}

Generated by [HubLab](https://hublab.dev) - Universal App Compiler

## Requirements

- Xcode 15.0+
- iOS ${this.config.minVersion}+
- Swift 5.9+

## Getting Started

1. Open \`${appName}.xcodeproj\` in Xcode
2. Select your target device/simulator
3. Press ⌘R to build and run

## Project Structure

\`\`\`
${appName}/
├── ${appName}App.swift      # App entry point
├── ContentView.swift         # Root view
├── Theme/
│   └── Colors.swift          # Theme colors & configuration
├── Components/               # HubLab capsule components
├── Screens/
│   └── HomeScreen.swift      # Main screen
├── Assets.xcassets/          # App icons & colors
└── Info.plist                # App configuration
\`\`\`

## Customization

### Colors
Edit \`Theme/Colors.swift\` to customize the color scheme.

### Components
All components in \`Components/\` are native SwiftUI views that you can customize.

## Publishing to App Store

1. Configure signing in Xcode
2. Update bundle identifier: \`${this.config.bundleId}\`
3. Archive: Product → Archive
4. Upload to App Store Connect

## Support

- Documentation: https://hublab.dev/docs
- Issues: https://github.com/hublab/hublab/issues
`,
      encoding: 'utf-8',
      language: 'markdown'
    }
  }

  // ============================================
  // HELPERS
  // ============================================

  private generateCapsuleViews(instance: CapsuleInstance, indent: number): string {
    const capsule = this.getCapsule(instance.capsuleId)
    if (!capsule) return `// Capsule not found: ${instance.capsuleId}`

    const viewName = this.toPascalCase(capsule.name)
    const props = this.generateSwiftProps(instance.props, capsule)
    const spaces = ' '.repeat(indent * 4)

    let view = `${spaces}${viewName}(${props})`

    if (instance.children && instance.children.length > 0) {
      const childViews = instance.children
        .map(child => this.generateCapsuleViews(child, indent + 1))
        .join('\n')
      view = `${spaces}${viewName}(${props}) {\n${childViews}\n${spaces}}`
    }

    return view
  }

  private generateSwiftProps(props: Record<string, unknown>, capsule: CapsuleDefinition): string {
    const propDefs = capsule.props
    const parts: string[] = []

    for (const [key, value] of Object.entries(props)) {
      const def = propDefs.find(p => p.name === key)
      const swiftKey = def?.platformMapping?.ios || key

      if (def?.type === 'action') {
        parts.push(`${swiftKey}: {}`)
      } else if (typeof value === 'string') {
        parts.push(`${swiftKey}: "${this.escapeString(value)}"`)
      } else if (typeof value === 'boolean') {
        parts.push(`${swiftKey}: ${value}`)
      } else if (typeof value === 'number') {
        parts.push(`${swiftKey}: ${value}`)
      }
    }

    return parts.join(', ')
  }

  private getSwiftLayout(composition: AppComposition): string {
    // Por ahora, layout simple VStack
    // TODO: Soportar más layouts
    return 'VStack(alignment: .leading, spacing: AppTheme.spacing)'
  }

  private getSwiftCornerRadius(radius: ThemeConfig['borderRadius']): string {
    const radii: Record<string, string> = {
      none: '0',
      sm: '4',
      md: '8',
      lg: '12',
      full: '100'
    }
    return radii[radius] || '8'
  }

  private generateCapabilityEntries(capabilities: string[]): string {
    const entries: string[] = []

    for (const cap of capabilities) {
      switch (cap) {
        case 'camera':
          entries.push(`    <key>NSCameraUsageDescription</key>
    <string>This app needs camera access</string>`)
          break
        case 'photo-library':
          entries.push(`    <key>NSPhotoLibraryUsageDescription</key>
    <string>This app needs photo library access</string>`)
          break
        case 'location':
          entries.push(`    <key>NSLocationWhenInUseUsageDescription</key>
    <string>This app needs location access</string>`)
          break
        case 'push-notifications':
          entries.push(`    <key>UIBackgroundModes</key>
    <array>
        <string>remote-notification</string>
    </array>`)
          break
      }
    }

    return entries.join('\n')
  }
}
