import type { CapsuleInstance, Screen } from './dnd-context'

// Generate SwiftUI code
export function generateSwiftUI(screens: Screen[], projectName: string, themeColor: string): string {
  const colorHex = themeColor.replace('#', '')

  let code = `import SwiftUI

// MARK: - ${projectName}
// Generated by HubLab - https://hublab.dev

@main
struct ${projectName.replace(/\s+/g, '')}App: App {
    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

// MARK: - Theme
extension Color {
    static let appPrimary = Color(hex: "${colorHex}")

    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        let a, r, g, b: UInt64
        switch hex.count {
        case 6: (a, r, g, b) = (255, int >> 16, int >> 8 & 0xFF, int & 0xFF)
        default: (a, r, g, b) = (255, 0, 0, 0)
        }
        self.init(.sRGB, red: Double(r) / 255, green: Double(g) / 255, blue: Double(b) / 255, opacity: Double(a) / 255)
    }
}

`

  // Generate view for each screen
  screens.forEach((screen, screenIndex) => {
    const viewName = screenIndex === 0 ? 'ContentView' : `${screen.name.replace(/\s+/g, '')}View`

    code += `// MARK: - ${screen.name}
struct ${viewName}: View {
    @State private var isLoading = false

    var body: some View {
        NavigationView {
            ScrollView {
                VStack(spacing: 16) {
`
    screen.capsules.forEach(c => {
      code += generateSwiftUIComponent(c, '                    ')
    })

    code += `                }
                .padding()
            }
            .navigationTitle("${screen.name}")
        }
    }
}

`
  })

  return code
}

function generateSwiftUIComponent(capsule: CapsuleInstance, indent: string): string {
  const props = capsule.props || {}

  switch (capsule.type) {
    case 'text':
      return `${indent}Text("${props.content || 'Hello'}")
${indent}    .font(.${props.size === 'lg' ? 'title' : props.size === 'sm' ? 'caption' : 'body'})
${indent}    ${props.bold ? '.fontWeight(.bold)' : ''}\n\n`

    case 'button':
      return `${indent}Button(action: { /* Action */ }) {
${indent}    Text("${props.text || 'Button'}")
${indent}        .fontWeight(.semibold)
${indent}        .frame(maxWidth: .infinity)
${indent}        .padding()
${indent}        .background(Color.appPrimary)
${indent}        .foregroundColor(.white)
${indent}        .cornerRadius(12)
${indent}}\n\n`

    case 'card':
      return `${indent}VStack(alignment: .leading, spacing: 8) {
${indent}    Text("${props.title || 'Title'}")
${indent}        .font(.headline)
${indent}    Text("${props.description || 'Description'}")
${indent}        .font(.subheadline)
${indent}        .foregroundColor(.gray)
${indent}}
${indent}.padding()
${indent}.background(Color(.systemBackground))
${indent}.cornerRadius(12)
${indent}.shadow(color: .black.opacity(0.1), radius: 5, x: 0, y: 2)\n\n`

    case 'input':
      return `${indent}TextField("${props.placeholder || 'Enter text'}", text: .constant(""))
${indent}    .textFieldStyle(.roundedBorder)
${indent}    .padding(.vertical, 4)\n\n`

    case 'switch':
      return `${indent}Toggle("${props.label || 'Option'}", isOn: .constant(${props.checked || false}))
${indent}    .toggleStyle(SwitchToggleStyle(tint: .appPrimary))\n\n`

    case 'progress':
      return `${indent}VStack(alignment: .leading, spacing: 4) {
${indent}    Text("Progress: ${props.value || 75}%")
${indent}        .font(.caption)
${indent}        .foregroundColor(.gray)
${indent}    ProgressView(value: ${(Number(props.value) || 75) / 100})
${indent}        .tint(.appPrimary)
${indent}}\n\n`

    case 'header':
      return `${indent}// Header handled by navigationTitle\n\n`

    case 'divider':
      return `${indent}Divider()\n\n`

    case 'spacer':
      return `${indent}Spacer().frame(height: ${props.size || 16})\n\n`

    case 'image':
      return `${indent}AsyncImage(url: URL(string: "${props.src || ''}")) { image in
${indent}    image.resizable().aspectRatio(contentMode: .fill)
${indent}} placeholder: {
${indent}    Rectangle().fill(Color.gray.opacity(0.2))
${indent}}
${indent}.frame(height: 200)
${indent}.cornerRadius(12)
${indent}.clipped()\n\n`

    case 'avatar':
      return `${indent}HStack {
${indent}    Circle()
${indent}        .fill(Color.appPrimary)
${indent}        .frame(width: ${props.size === 'lg' ? 60 : props.size === 'sm' ? 32 : 40}, height: ${props.size === 'lg' ? 60 : props.size === 'sm' ? 32 : 40})
${indent}        .overlay(Text("${(props.name as string || 'U')[0]}").foregroundColor(.white).fontWeight(.semibold))
${indent}    Text("${props.name || 'User'}")
${indent}}\n\n`

    case 'list':
      return `${indent}ForEach(0..<${props.items || 3}, id: \\.self) { index in
${indent}    HStack {
${indent}        Circle().fill(Color.gray.opacity(0.2)).frame(width: 40, height: 40)
${indent}        VStack(alignment: .leading) {
${indent}            Text("Item \\(index + 1)").font(.subheadline).fontWeight(.medium)
${indent}            Text("Description").font(.caption).foregroundColor(.gray)
${indent}        }
${indent}        Spacer()
${indent}    }
${indent}    .padding(.vertical, 8)
${indent}    ${props.showDivider ? 'Divider()' : ''}
${indent}}\n\n`

    default:
      return `${indent}// ${capsule.name} component placeholder\n${indent}Text("${capsule.name}")\n\n`
  }
}

// Generate Kotlin/Jetpack Compose code
export function generateKotlin(screens: Screen[], projectName: string, themeColor: string): string {
  const packageName = projectName.toLowerCase().replace(/\s+/g, '')

  let code = `package com.hublab.${packageName}

// Generated by HubLab - https://hublab.dev

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController

// Theme Color
val AppPrimary = Color(0xFF${themeColor.replace('#', '')})

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme(
                colorScheme = lightColorScheme(
                    primary = AppPrimary,
                    onPrimary = Color.White
                )
            ) {
                MainNavigation()
            }
        }
    }
}

@Composable
fun MainNavigation() {
    val navController = rememberNavController()
    NavHost(navController = navController, startDestination = "home") {
${screens.map((s, i) => `        composable("${i === 0 ? 'home' : s.name.toLowerCase().replace(/\s+/g, '_')}") { ${s.name.replace(/\s+/g, '')}Screen() }`).join('\n')}
    }
}

`

  // Generate composable for each screen
  screens.forEach(screen => {
    code += `@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun ${screen.name.replace(/\s+/g, '')}Screen() {
    Scaffold(
        topBar = {
            TopAppBar(
                title = { Text("${screen.name}") },
                colors = TopAppBarDefaults.topAppBarColors(containerColor = AppPrimary, titleContentColor = Color.White)
            )
        }
    ) { padding ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(16.dp),
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
`
    screen.capsules.forEach(c => {
      code += generateKotlinComponent(c, '            ')
    })

    code += `        }
    }
}

`
  })

  return code
}

function generateKotlinComponent(capsule: CapsuleInstance, indent: string): string {
  const props = capsule.props || {}

  switch (capsule.type) {
    case 'text':
      return `${indent}item {
${indent}    Text(
${indent}        text = "${props.content || 'Hello'}",
${indent}        style = MaterialTheme.typography.${props.size === 'lg' ? 'headlineMedium' : props.size === 'sm' ? 'bodySmall' : 'bodyLarge'},
${indent}        fontWeight = ${props.bold ? 'FontWeight.Bold' : 'FontWeight.Normal'}
${indent}    )
${indent}}\n`

    case 'button':
      return `${indent}item {
${indent}    Button(
${indent}        onClick = { /* Action */ },
${indent}        modifier = Modifier.fillMaxWidth(),
${indent}        colors = ButtonDefaults.buttonColors(containerColor = AppPrimary)
${indent}    ) {
${indent}        Text("${props.text || 'Button'}", fontWeight = FontWeight.SemiBold)
${indent}    }
${indent}}\n`

    case 'card':
      return `${indent}item {
${indent}    Card(
${indent}        modifier = Modifier.fillMaxWidth(),
${indent}        colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surface)
${indent}    ) {
${indent}        Column(modifier = Modifier.padding(16.dp)) {
${indent}            Text("${props.title || 'Title'}", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)
${indent}            Spacer(modifier = Modifier.height(4.dp))
${indent}            Text("${props.description || 'Description'}", style = MaterialTheme.typography.bodyMedium, color = Color.Gray)
${indent}        }
${indent}    }
${indent}}\n`

    case 'input':
      return `${indent}item {
${indent}    var text by remember { mutableStateOf("") }
${indent}    OutlinedTextField(
${indent}        value = text,
${indent}        onValueChange = { text = it },
${indent}        label = { Text("${props.label || props.placeholder || 'Input'}") },
${indent}        modifier = Modifier.fillMaxWidth()
${indent}    )
${indent}}\n`

    case 'switch':
      return `${indent}item {
${indent}    var checked by remember { mutableStateOf(${props.checked || false}) }
${indent}    Row(
${indent}        modifier = Modifier.fillMaxWidth(),
${indent}        horizontalArrangement = Arrangement.SpaceBetween,
${indent}        verticalAlignment = Alignment.CenterVertically
${indent}    ) {
${indent}        Text("${props.label || 'Option'}")
${indent}        Switch(checked = checked, onCheckedChange = { checked = it }, colors = SwitchDefaults.colors(checkedThumbColor = AppPrimary))
${indent}    }
${indent}}\n`

    case 'progress':
      return `${indent}item {
${indent}    Column {
${indent}        Text("Progress: ${props.value || 75}%", style = MaterialTheme.typography.bodySmall, color = Color.Gray)
${indent}        Spacer(modifier = Modifier.height(4.dp))
${indent}        LinearProgressIndicator(
${indent}            progress = ${(Number(props.value) || 75) / 100}f,
${indent}            modifier = Modifier.fillMaxWidth(),
${indent}            color = AppPrimary
${indent}        )
${indent}    }
${indent}}\n`

    case 'divider':
      return `${indent}item { Divider() }\n`

    case 'spacer':
      return `${indent}item { Spacer(modifier = Modifier.height(${props.size || 16}.dp)) }\n`

    default:
      return `${indent}item {
${indent}    // ${capsule.name} component placeholder
${indent}    Text("${capsule.name}")
${indent}}\n`
  }
}

// Generate React/Next.js code
export function generateReact(screens: Screen[], projectName: string, themeColor: string): string {
  const componentName = projectName.replace(/\s+/g, '')

  let code = `// ${projectName}
// Generated by HubLab - https://hublab.dev

import React, { useState } from 'react'

// Theme
const theme = {
  primary: '${themeColor}',
  primaryHover: '${adjustColor(themeColor, -20)}',
}

`

  // Generate component for each screen
  screens.forEach((screen, index) => {
    const screenName = index === 0 ? componentName : `${screen.name.replace(/\s+/g, '')}`

    code += `export ${index === 0 ? 'default ' : ''}function ${screenName}() {
  const [loading, setLoading] = useState(false)

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b sticky top-0 z-10">
        <div className="max-w-2xl mx-auto px-4 py-4 flex items-center justify-between">
          <h1 className="text-xl font-semibold text-gray-900">${screen.name}</h1>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-2xl mx-auto px-4 py-6 space-y-4">
`
    screen.capsules.forEach(c => {
      code += generateReactComponent(c, '        ', themeColor)
    })

    code += `      </main>
    </div>
  )
}

`
  })

  // Add CSS-in-JS styles
  code += `// Tailwind CSS classes are used. Make sure to install:
// npm install -D tailwindcss postcss autoprefixer
// npx tailwindcss init -p

// tailwind.config.js
// module.exports = {
//   content: ['./src/**/*.{js,ts,jsx,tsx}'],
//   theme: {
//     extend: {
//       colors: {
//         primary: '${themeColor}',
//       },
//     },
//   },
//   plugins: [],
// }
`

  return code
}

function generateReactComponent(capsule: CapsuleInstance, indent: string, themeColor: string): string {
  const props = capsule.props || {}

  switch (capsule.type) {
    case 'text':
      return `${indent}<p className="${props.size === 'lg' ? 'text-2xl' : props.size === 'sm' ? 'text-sm' : 'text-base'} ${props.bold ? 'font-bold' : ''} text-gray-900">
${indent}  ${props.content || 'Hello World'}
${indent}</p>\n\n`

    case 'button':
      return `${indent}<button
${indent}  className="w-full px-4 py-3 rounded-xl text-white font-semibold transition-all hover:opacity-90 active:scale-[0.98]"
${indent}  style={{ backgroundColor: '${themeColor}' }}
${indent}  onClick={() => console.log('clicked')}
${indent}>
${indent}  ${props.text || 'Button'}
${indent}</button>\n\n`

    case 'card':
      return `${indent}<div className="bg-white rounded-xl p-4 shadow-sm border border-gray-100">
${indent}  <h3 className="font-semibold text-gray-900">${props.title || 'Card Title'}</h3>
${indent}  <p className="text-gray-600 text-sm mt-1">${props.description || 'Card description'}</p>
${indent}</div>\n\n`

    case 'input':
      return `${indent}<input
${indent}  type="text"
${indent}  placeholder="${props.placeholder || 'Enter text...'}"
${indent}  className="w-full px-4 py-3 bg-white border border-gray-200 rounded-xl focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none transition-all"
${indent}/>\n\n`

    case 'switch':
      return `${indent}<label className="flex items-center justify-between cursor-pointer">
${indent}  <span className="text-gray-700">${props.label || 'Option'}</span>
${indent}  <div className="relative">
${indent}    <input type="checkbox" className="sr-only peer" defaultChecked={${props.checked || false}} />
${indent}    <div className="w-11 h-6 bg-gray-200 rounded-full peer peer-checked:bg-indigo-500 transition-colors"></div>
${indent}    <div className="absolute left-1 top-1 w-4 h-4 bg-white rounded-full shadow peer-checked:translate-x-5 transition-transform"></div>
${indent}  </div>
${indent}</label>\n\n`

    case 'progress':
      return `${indent}<div>
${indent}  <div className="flex justify-between text-sm text-gray-600 mb-1">
${indent}    <span>Progress</span>
${indent}    <span>${props.value || 75}%</span>
${indent}  </div>
${indent}  <div className="w-full h-2 bg-gray-200 rounded-full overflow-hidden">
${indent}    <div className="h-full rounded-full transition-all" style={{ width: '${props.value || 75}%', backgroundColor: '${themeColor}' }}></div>
${indent}  </div>
${indent}</div>\n\n`

    case 'image':
      return `${indent}<div className="w-full h-48 bg-gray-200 rounded-xl overflow-hidden">
${indent}  {/* Add your image here */}
${indent}  <div className="w-full h-full flex items-center justify-center text-gray-400">
${indent}    <svg className="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24">
${indent}      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
${indent}    </svg>
${indent}  </div>
${indent}</div>\n\n`

    case 'divider':
      return `${indent}<hr className="border-gray-200" />\n\n`

    case 'spacer':
      return `${indent}<div style={{ height: ${props.size || 16} }}></div>\n\n`

    case 'list':
      return `${indent}<div className="divide-y divide-gray-100">
${indent}  {Array.from({ length: ${props.items || 3} }).map((_, i) => (
${indent}    <div key={i} className="flex items-center gap-3 py-3">
${indent}      <div className="w-10 h-10 rounded-full bg-gray-200"></div>
${indent}      <div className="flex-1">
${indent}        <div className="font-medium text-gray-900">Item {i + 1}</div>
${indent}        <div className="text-sm text-gray-500">Description</div>
${indent}      </div>
${indent}    </div>
${indent}  ))}
${indent}</div>\n\n`

    default:
      return `${indent}{/* ${capsule.name} component */}
${indent}<div className="p-4 bg-gray-100 rounded-xl border border-dashed border-gray-300 text-center text-gray-500">
${indent}  ${capsule.icon} ${capsule.name}
${indent}</div>\n\n`
  }
}

// Utility to darken/lighten color
function adjustColor(hex: string, amount: number): string {
  const color = hex.replace('#', '')
  const num = parseInt(color, 16)
  const r = Math.min(255, Math.max(0, (num >> 16) + amount))
  const g = Math.min(255, Math.max(0, ((num >> 8) & 0x00FF) + amount))
  const b = Math.min(255, Math.max(0, (num & 0x0000FF) + amount))
  return `#${((r << 16) | (g << 8) | b).toString(16).padStart(6, '0')}`
}

// Generate Tauri/Desktop code
export function generateTauri(screens: Screen[], projectName: string, themeColor: string): string {
  // Tauri uses web technologies, so we return React code with Tauri-specific additions
  let code = `// ${projectName} - Desktop App
// Generated by HubLab - https://hublab.dev
// Built with Tauri + React

// Run: npm create tauri-app@latest
// Then replace src/App.tsx with this code

import { useState, useEffect } from 'react'
import { invoke } from '@tauri-apps/api/tauri'
import { appWindow } from '@tauri-apps/api/window'

const theme = {
  primary: '${themeColor}',
}

export default function App() {
  const [isMaximized, setIsMaximized] = useState(false)

  useEffect(() => {
    // Listen for window state changes
    const unlisten = appWindow.onResized(() => {
      appWindow.isMaximized().then(setIsMaximized)
    })
    return () => { unlisten.then(f => f()) }
  }, [])

  return (
    <div className="min-h-screen bg-gray-900 text-white">
      {/* Custom Title Bar */}
      <div
        data-tauri-drag-region
        className="h-10 bg-gray-800 flex items-center justify-between px-4 select-none"
      >
        <span className="text-sm font-medium">${projectName}</span>
        <div className="flex items-center gap-1">
          <button
            onClick={() => appWindow.minimize()}
            className="w-8 h-8 rounded hover:bg-gray-700 flex items-center justify-center"
          >
            −
          </button>
          <button
            onClick={() => appWindow.toggleMaximize()}
            className="w-8 h-8 rounded hover:bg-gray-700 flex items-center justify-center"
          >
            {isMaximized ? '❐' : '□'}
          </button>
          <button
            onClick={() => appWindow.close()}
            className="w-8 h-8 rounded hover:bg-red-500 flex items-center justify-center"
          >
            ×
          </button>
        </div>
      </div>

      {/* Content */}
      <main className="p-6 space-y-4">
`

  screens[0]?.capsules.forEach(c => {
    code += generateReactComponent(c, '        ', themeColor)
  })

  code += `      </main>
    </div>
  )
}

// tauri.conf.json additions:
// {
//   "tauri": {
//     "windows": [{
//       "decorations": false,
//       "transparent": true,
//       "width": 800,
//       "height": 600
//     }]
//   }
// }
`

  return code
}
